package com.dafeng.upgrade.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TB_IMGS.
 */
public class TbImgs {

    private Long id;
    /** Not-null value. */
    private String name;
    private String curVer;
    private String latestVer;
    private String downloadUrl;
    private Long downloadId;

    public TbImgs() {
    }

    public TbImgs(Long id) {
        this.id = id;
    }

    public TbImgs(Long id, String name, String curVer, String latestVer, String downloadUrl, Long downloadId) {
        this.id = id;
        this.name = name;
        this.curVer = curVer;
        this.latestVer = latestVer;
        this.downloadUrl = downloadUrl;
        this.downloadId = downloadId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getCurVer() {
        return curVer;
    }

    public void setCurVer(String curVer) {
        this.curVer = curVer;
    }

    public String getLatestVer() {
        return latestVer;
    }

    public void setLatestVer(String latestVer) {
        this.latestVer = latestVer;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public Long getDownloadId() {
        return downloadId;
    }

    public void setDownloadId(Long downloadId) {
        this.downloadId = downloadId;
    }

}
